# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:lincc-frameworks/python-project-template
author_email: seanmcgu@andrew.cmu.edu
author_name: LINCC Frameworks
create_example_module: false
custom_install: custom
enforce_style: []
failure_notification: []
include_benchmarks: false
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: lbench
project_description: Benchmarking tools for LSDB
project_license: MIT
project_name: lbench
project_organization: lincc-frameworks
python_versions:
- '3.10'
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
